### ISSUE TITLE
Pr 3: hayTesoroEn no es correcta 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [KBRIEL/EstrD2023s1#29]
moverN :: Int -> Camino -> Camino
moverN     0      c             =  c
moverN     n      Fin           =  error "no existen esa cantidad de pasos" --> No puede ser Parcial
moverN     n     (Nada c)       =  moverN (n -1) c
moverN     n     (Cofre os c)   =  moverN (n -1) c

hayTesoroAqui :: Camino -> Bool
hayTesoroAqui    Fin         = False  --> Mismo caso el Tercero ¿Es necesario poner este caso de esta manera?
hayTesoroAqui    (Cofre os c)= contieneTesoro os
hayTesoroAqui    (Nada c)    =  False --> Mismo caso el Primero ¿Es necesario poner este caso de esta manera?

hayTesoroEn :: Int -> Camino -> Bool
hayTesoroEn    0       ca    =  hayTesoroAqui   ca
hayTesoroEn    n       ca     = hayTesoroAqui (moverN n ca )  --> Este caso ya abarca el primer caso

**Comment by KBRIEL** [comment]
moverN n Fin = error "no existen esa cantidad de pasos" --> No puede ser Parcial
esto significa que termina acá aunque n sea mayor al camino recorrido o que al menos hay n pasos?
moverN     n      Fin           = Fin
