### ISSUE TITLE
Pr.1: La función yTambien es incorrecta 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [KBRIEL/EstrD2023s1#5]
La idea es no usar la función &&.

**Comment by JuanIgnGarcia** [comment]
La función yTambien ahora hace doble PM.
Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by JuanIgnGarcia** [comment]
Esta bien pero hay un detalle que se puede mejorar 
yTambien :: Bool -> Bool -> Bool
yTambien    True     b    = b
yTambien    False    _    = False   ---> ¿Es necesario que ver si es False?

**Comment by KBRIEL** [comment]
Hola Juan
Disculpa hay algo que no entiendo
si no pongo este caso
yTambien False _ = False ---> ¿Es necesario que ver si es False?
cuando la función queda
yTambien :: Bool -> Bool -> Bool
yTambien True b = b
en caso del que el primer parámetro sea False, no rompería?
No me queda claro eso, sino mañana te consulto en clase
gracias

**Comment by JuanIgnGarcia** [comment]
yTambien :: Bool -> Bool -> Bool
yTambien    True     b    = b
yTambien    False    _    = False --> Si no es True tiene que ser False , no es necesario ponerlo podes poner _
